name: Deploy DocumentDB

on:
  push:
    branches:
      - main  # Personalize de acordo com sua ramificação principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_USERNAME: ${{ secrets.AWS_DOCUMENTDB_USER }}
      DB_PASSWORD: ${{ secrets.AWS_DOCUMENTDB_PASSWORD }}

    steps:
    - name: Clonado o repositorio
      uses: actions/checkout@v2

    - name: Inicilizando o Terraform...
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.2  
        
    - name: Confugurando Credenciais da AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1
      env:
        AWS_REGION: us-east-1 
    
    # - name: Entrando no diretorio /terraform
    #   run: cd /terraform

    - name: Set environment variables for Terraform
      run: |
        export TF_VAR_db_username=$DB_USERNAME
        export TF_VAR_db_password=$DB_PASSWORD

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve
      continue-on-error: true

    - name: Terraform Show
      run: terraform show

    - name: Terraform Destroy
      run: |
        terraform destroy -input=false -auto-approve
        rm -f aws_access_key_id
        rm -f aws_secret_access_key
      continue-on-error: true
